// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: emails.sql

package db

import (
	"context"
)

const getEmailByID = `-- name: GetEmailByID :one
SELECT
  id,
  message_id,
  in_reply_to,
  "references",
  thread_id,
  subject,
  sender_name,
  sender_email,
  receiver_name,
  receiver_email,
  raw_body,
  text_body,
  attachments,
  sent_at,
  received_at,
  s3_key,
  created_at
FROM emails
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetEmailByID(ctx context.Context, id int64) (Emails, error) {
	row := q.db.QueryRowContext(ctx, getEmailByID, id)
	var i Emails
	err := row.Scan(
		&i.ID,
		&i.MessageID,
		&i.InReplyTo,
		&i.References,
		&i.ThreadID,
		&i.Subject,
		&i.SenderName,
		&i.SenderEmail,
		&i.ReceiverName,
		&i.ReceiverEmail,
		&i.RawBody,
		&i.TextBody,
		&i.Attachments,
		&i.SentAt,
		&i.ReceivedAt,
		&i.S3Key,
		&i.CreatedAt,
	)
	return i, err
}
