// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

type Emails struct {
	ID            int64                 `json:"id"`
	MessageID     sql.NullString        `json:"message_id"`
	InReplyTo     sql.NullString        `json:"in_reply_to"`
	References    sql.NullString        `json:"references"`
	ThreadID      sql.NullInt64         `json:"thread_id"`
	Subject       sql.NullString        `json:"subject"`
	SenderName    sql.NullString        `json:"sender_name"`
	SenderEmail   sql.NullString        `json:"sender_email"`
	ReceiverName  sql.NullString        `json:"receiver_name"`
	ReceiverEmail sql.NullString        `json:"receiver_email"`
	RawBody       sql.NullString        `json:"raw_body"`
	TextBody      sql.NullString        `json:"text_body"`
	Attachments   pqtype.NullRawMessage `json:"attachments"`
	SentAt        sql.NullTime          `json:"sent_at"`
	ReceivedAt    sql.NullTime          `json:"received_at"`
	S3Key         sql.NullString        `json:"s3_key"`
	CreatedAt     sql.NullTime          `json:"created_at"`
}

type Threads struct {
	ID        int64          `json:"id"`
	Subject   sql.NullString `json:"subject"`
	CreatedAt sql.NullTime   `json:"created_at"`
}
