// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: gmail_accounts.sql

package db

import (
	"context"
	"time"
)

const getGmailCredentialsByTenantName = `-- name: GetGmailCredentialsByTenantName :many
SELECT id, tenant_name, email, client_id, client_secret, access_token, refresh_token, token_expiry, created_at, updated_at FROM gmail_credentials
WHERE tenant_name = $1
`

func (q *Queries) GetGmailCredentialsByTenantName(ctx context.Context, tenantName string) ([]GmailCredential, error) {
	rows, err := q.db.QueryContext(ctx, getGmailCredentialsByTenantName, tenantName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GmailCredential
	for rows.Next() {
		var i GmailCredential
		if err := rows.Scan(
			&i.ID,
			&i.TenantName,
			&i.Email,
			&i.ClientID,
			&i.ClientSecret,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOneGmailCredentialByEmail = `-- name: GetOneGmailCredentialByEmail :one
SELECT id, tenant_name, email, client_id, client_secret, access_token, refresh_token, token_expiry, created_at, updated_at FROM gmail_credentials
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetOneGmailCredentialByEmail(ctx context.Context, email string) (GmailCredential, error) {
	row := q.db.QueryRowContext(ctx, getOneGmailCredentialByEmail, email)
	var i GmailCredential
	err := row.Scan(
		&i.ID,
		&i.TenantName,
		&i.Email,
		&i.ClientID,
		&i.ClientSecret,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenExpiry,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listGmailCredentials = `-- name: ListGmailCredentials :many
SELECT id, tenant_name, email, client_id, client_secret, access_token, refresh_token, token_expiry, created_at, updated_at FROM gmail_credentials
WHERE tenant_name = $1
`

func (q *Queries) ListGmailCredentials(ctx context.Context, tenantName string) ([]GmailCredential, error) {
	rows, err := q.db.QueryContext(ctx, listGmailCredentials, tenantName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GmailCredential
	for rows.Next() {
		var i GmailCredential
		if err := rows.Scan(
			&i.ID,
			&i.TenantName,
			&i.Email,
			&i.ClientID,
			&i.ClientSecret,
			&i.AccessToken,
			&i.RefreshToken,
			&i.TokenExpiry,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertToken = `-- name: UpsertToken :exec
INSERT INTO gmail_credentials (
    tenant_name, email, client_id, client_secret,
    access_token, refresh_token, token_expiry
) VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (tenant_name, email)
DO UPDATE SET
    client_id = EXCLUDED.client_id,
    client_secret = EXCLUDED.client_secret,
    access_token = EXCLUDED.access_token,
    refresh_token = EXCLUDED.refresh_token,
    token_expiry = EXCLUDED.token_expiry,
    updated_at = CURRENT_TIMESTAMP
`

type UpsertTokenParams struct {
	TenantName   string    `json:"tenant_name"`
	Email        string    `json:"email"`
	ClientID     string    `json:"client_id"`
	ClientSecret string    `json:"client_secret"`
	AccessToken  string    `json:"access_token"`
	RefreshToken string    `json:"refresh_token"`
	TokenExpiry  time.Time `json:"token_expiry"`
}

func (q *Queries) UpsertToken(ctx context.Context, arg UpsertTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertToken,
		arg.TenantName,
		arg.Email,
		arg.ClientID,
		arg.ClientSecret,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenExpiry,
	)
	return err
}
