// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"database/sql"
	"time"
)

type GmailCredential struct {
	ID           int32        `json:"id"`
	TenantName   string       `json:"tenant_name"`
	Email        string       `json:"email"`
	ClientID     string       `json:"client_id"`
	ClientSecret string       `json:"client_secret"`
	AccessToken  string       `json:"access_token"`
	RefreshToken string       `json:"refresh_token"`
	TokenExpiry  time.Time    `json:"token_expiry"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
}
