// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: emails.sql

package db

import (
	"context"
	"database/sql"

	"github.com/sqlc-dev/pqtype"
)

const createEmail = `-- name: CreateEmail :one
INSERT INTO emails (
    subject, sender_name, sender_email, receiver_name, receiver_email,
    raw_body, text_body, attachments, sent_at, received_at, s3_key
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10, $11
) RETURNING id
`

type CreateEmailParams struct {
	Subject       sql.NullString        `json:"subject"`
	SenderName    sql.NullString        `json:"sender_name"`
	SenderEmail   sql.NullString        `json:"sender_email"`
	ReceiverName  sql.NullString        `json:"receiver_name"`
	ReceiverEmail sql.NullString        `json:"receiver_email"`
	RawBody       sql.NullString        `json:"raw_body"`
	TextBody      sql.NullString        `json:"text_body"`
	Attachments   pqtype.NullRawMessage `json:"attachments"`
	SentAt        sql.NullTime          `json:"sent_at"`
	ReceivedAt    sql.NullTime          `json:"received_at"`
	S3Key         sql.NullString        `json:"s3_key"`
}

func (q *Queries) CreateEmail(ctx context.Context, arg CreateEmailParams) (int32, error) {
	row := q.db.QueryRowContext(ctx, createEmail,
		arg.Subject,
		arg.SenderName,
		arg.SenderEmail,
		arg.ReceiverName,
		arg.ReceiverEmail,
		arg.RawBody,
		arg.TextBody,
		arg.Attachments,
		arg.SentAt,
		arg.ReceivedAt,
		arg.S3Key,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}
